Repository openrewrite/rewrite-liberty, pull requests merged in 2023-08, with the labels that each got.

#1 Initial structure
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/repository-backup.yml
  .gitignore
  README.md
  build.gradle.kts
  gradle/licenseHeader.txt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/resources/META-INF/rewrite/category.yml
  src/main/resources/META-INF/rewrite/openliberty-23.yml
Labels: good first issue

#2 7 added tWAS to liberty recipes
  .gitignore
  build.gradle.kts
  src/main/java/org/openrewrite/java/liberty/ChangeMethodInvocation.java
  src/main/java/org/openrewrite/java/liberty/ChangeStringLiteral.java
  src/main/java/org/openrewrite/java/liberty/RemoveWas2LibertyNonPortableJndiLookup.java
  src/main/java/org/openrewrite/xml/liberty/PersistenceXmlLocationRule.java
  src/main/resources/META-INF/rewrite/openliberty-23.yml
  src/main/resources/META-INF/rewrite/was-to-liberty.yml
  src/test/java/org/openrewrite/.editorconfig
  src/test/java/org/openrewrite/java/liberty/InvalidInitialContextTest.java
  src/test/java/org/openrewrite/java/liberty/RemoveWas2LibertyNonPortableJndiLookupTest.java
  src/test/java/org/openrewrite/java/liberty/ServerNameTest.java
  src/test/java/org/openrewrite/xml/liberty/AppDDNamespaceTest.java
  src/test/java/org/openrewrite/xml/liberty/ConnectorDDNamespaceTest.java
  src/test/java/org/openrewrite/xml/liberty/EJBDDNamespaceTest.java
  src/test/java/org/openrewrite/xml/liberty/PersistenceXmlLocationRuleTest.java
  src/test/java/org/openrewrite/xml/liberty/WebDDNamespaceTest.java
Labels: recipe

#3 Replace `WSSecurityHelper.getLTPACookieFromSSOToken` and `revokeSSOCookies`
  .gitignore
  src/main/java/org/openrewrite/java/liberty/ChangeMethodInvocation.java
  src/main/java/org/openrewrite/java/liberty/RemoveWas2LibertyNonPortableJndiLookup.java
  src/main/java/org/openrewrite/java/liberty/WebSphereUnavailableSSOCookieMethod.java
  src/main/java/org/openrewrite/xml/liberty/PersistenceXmlLocationRule.java
  src/main/resources/META-INF/rewrite/classpath/websecurity_logout_test.jar
  src/main/resources/META-INF/rewrite/classpath/websecurity_test.jar
  src/main/resources/META-INF/rewrite/was-to-liberty.yml
  src/test/java/org/openrewrite/java/liberty/.editorconfig
  src/test/java/org/openrewrite/java/liberty/InvalidInitialContextTest.java
  src/test/java/org/openrewrite/java/liberty/RemoveWas2LibertyNonPortableJndiLookupTest.java
  src/test/java/org/openrewrite/java/liberty/ServerNameTest.java
  src/test/java/org/openrewrite/java/liberty/UnavailableSSOTokenTest.java
  src/test/java/org/openrewrite/java/liberty/WebSphereUnavailableSSOCookieMethodTest.java
  src/test/java/org/openrewrite/xml/liberty/PersistenceXmlLocationRuleTest.java
Labels: recipe

#6 Fixed SSO token rule and updated readme
  README.md
  src/main/resources/META-INF/rewrite/was-to-liberty.yml
  src/test/java/org/openrewrite/java/liberty/UnavailableSSOTokenTest.java
Labels: bug, documentation
